#!/bin/bash
# Stratara OS Secure Boot Setup Script
# This script sets up Secure Boot for the Stratara OS ISO

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

# Configuration
SHIM_SOURCE="/usr/share/shim/shimx64.efi"
MOK_SOURCE="/usr/share/shim/mmx64.efi"
GRUB_SOURCE="/usr/lib/grub/x86_64-efi-signed/grubx64.efi"
EFI_DIR="/boot/efi"
EFI_BOOT_DIR="$EFI_DIR/EFI/BOOT"
EFI_STRATARA_DIR="$EFI_DIR/EFI/stratara"
MOK_DIR="/var/lib/shim-signed/mok"

log_info "Setting up Secure Boot for Stratara OS..."

# Check if Secure Boot is supported
if [[ ! -d /sys/firmware/efi ]]; then
    log_warning "System is not booted in UEFI mode, skipping Secure Boot setup"
    exit 0
fi

# Check if shim is available
if [[ ! -f "$SHIM_SOURCE" ]]; then
    log_warning "Shim not found at $SHIM_SOURCE, installing shim package"
    zypper install -y shim || log_error "Failed to install shim"
fi

# Create EFI directories
log_info "Creating EFI directories..."
mkdir -p "$EFI_BOOT_DIR"
mkdir -p "$EFI_STRATARA_DIR"
mkdir -p "$MOK_DIR"

# Copy shim
log_info "Installing shim..."
if [[ -f "$SHIM_SOURCE" ]]; then
    cp "$SHIM_SOURCE" "$EFI_BOOT_DIR/BOOTX64.EFI"
    cp "$SHIM_SOURCE" "$EFI_STRATARA_DIR/grubx64.efi"
    log_success "Shim installed"
else
    log_error "Shim source not found"
    exit 1
fi

# Copy MOK manager
log_info "Installing MOK manager..."
if [[ -f "$MOK_SOURCE" ]]; then
    cp "$MOK_SOURCE" "$EFI_BOOT_DIR/mmx64.efi"
    cp "$MOK_SOURCE" "$EFI_STRATARA_DIR/mmx64.efi"
    log_success "MOK manager installed"
else
    log_warning "MOK manager source not found"
fi

# Copy signed GRUB
log_info "Installing signed GRUB..."
if [[ -f "$GRUB_SOURCE" ]]; then
    cp "$GRUB_SOURCE" "$EFI_STRATARA_DIR/grubx64.efi.signed"
    log_success "Signed GRUB installed"
else
    log_warning "Signed GRUB not found at $GRUB_SOURCE"
fi

# Create GRUB config for Secure Boot
log_info "Creating GRUB configuration..."
cat > "$EFI_STRATARA_DIR/grub.cfg" << 'EOF'
# Stratara OS GRUB Configuration for Secure Boot
# This file is generated by the Stratara Secure Boot setup script

set timeout=5
set default=0

# Theme
if [ -f /usr/share/grub/themes/stratara/theme.txt ]; then
    source /usr/share/grub/themes/stratara/theme.txt
fi

# Resolution
insmod gfxterm
insmod gfxmenu
set gfxmode=1920x1080
set gfxpayload=keep

# Font
if loadfont /usr/share/grub/themes/stratara/fonts/NotoSans-Regular.pf2; then
    set gfxmode=auto
    insmod efi_gop
    insmod efi_uga
    insmod video_bochs
    insmod video_cirrus
    insmod gfxterm
    terminal_output gfxterm
fi

# Menu entries
menuentry 'Stratara OS' --class stratara --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple' {
    load_video
    set gfxpayload=keep
    insmod gzio
    insmod part_gpt
    insmod ext2
    insmod btrfs
    insmod xfs
    insmod f2fs
    
    # Find root filesystem
    search --no-floppy --fs-uuid --set=root ${ROOT_UUID}
    
    echo 'Loading Stratara OS...'
    linux /boot/vmlinuz root=UUID=${ROOT_UUID} ro quiet splash=silent vt.global_cursor_default=0 loglevel=3 systemd.show_status=auto rd.udev.log_level=3 module.sig_enforce=1 lock_down=1
    echo 'Loading initial ramdisk...'
    initrd /boot/initrd
}

menuentry 'Stratara OS (Recovery Mode)' --class stratara --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-recovery' {
    load_video
    set gfxpayload=keep
    insmod gzio
    insmod part_gpt
    insmod ext2
    insmod btrfs
    insmod xfs
    insmod f2fs
    
    search --no-floppy --fs-uuid --set=root ${ROOT_UUID}
    
    echo 'Loading Stratara OS (Recovery)...'
    linux /boot/vmlinuz root=UUID=${ROOT_UUID} ro single systemd.unit=emergency.target quiet loglevel=3 systemd.show_status=auto rd.udev.log_level=3
    initrd /boot/initrd
}

menuentry 'UEFI Firmware Settings' --class uefi --class os $menuentry_id_option 'uefi-firmware' {
    fwsetup
}

# Submenu for advanced options
submenu 'Advanced options for Stratara OS' {
    menuentry 'Stratara OS (with Linux kernel)' --class stratara --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-advanced' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_gpt
        insmod ext2
        insmod btrfs
        insmod xfs
        insmod f2fs
        
        search --no-floppy --fs-uuid --set=root ${ROOT_UUID}
        
        linux /boot/vmlinuz root=UUID=${ROOT_UUID} ro quiet splash=silent vt.global_cursor_default=0 loglevel=3 systemd.show_status=auto rd.udev.log_level=3 module.sig_enforce=1 lock_down=1
        initrd /boot/initrd
    }
    
    menuentry 'Stratara OS (with Linux kernel - nomodeset)' --class stratara --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-nomodeset' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_gpt
        insmod ext2
        insmod btrfs
        insmod xfs
        insmod f2fs
        
        search --no-floppy --fs-uuid --set=root ${ROOT_UUID}
        
        linux /boot/vmlinuz root=UUID=${ROOT_UUID} ro quiet nomodeset vt.global_cursor_default=0 loglevel=3 systemd.show_status=auto rd.udev.log_level=3
        initrd /boot/initrd
    }
}
EOF

log_success "GRUB configuration created"

# Enroll MOK (Machine Owner Key)
log_info "Enrolling MOK..."
if command -v mokutil &> /dev/null; then
    # Generate MOK key pair if not exists
    if [[ ! -f "$MOK_DIR/MOK.priv" ]] || [[ ! -f "$MOK_DIR/MOK.der" ]]; then
        log_info "Generating MOK key pair..."
        openssl req -new -x509 -newkey rsa:2048 -keyout "$MOK_DIR/MOK.priv" -outform DER -out "$MOK_DIR/MOK.der" -nodes -days 3650 -subj "/CN=Stratara OS Secure Boot/"
        chmod 600 "$MOK_DIR/MOK.priv"
        log_success "MOK key pair generated"
    fi
    
    # Import MOK
    if mokutil --import "$MOK_DIR/MOK.der" --root-pw <<< "stratara"; then
        log_success "MOK enrolled successfully"
    else
        log_warning "MOK enrollment failed, manual enrollment required on first boot"
    fi
else
    log_warning "mokutil not found, skipping MOK enrollment"
fi

# Update boot order
log_info "Updating boot order..."
efibootmgr -c -d /dev/sda -p 1 -L "Stratara OS" -l '\EFI\stratara\grubx64.efi' || log_warning "Failed to add boot entry"

log_success "Secure Boot setup completed!"
log_info "Note: MOK enrollment requires user confirmation on first boot"